// ATLSysHandleReader.idl : ATLSysHandleReader的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(ATLSysHandleReader.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,	
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(687EA368-2BF0-4DB8-BAB3-AFDA1720C666),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IInfoReader : IDispatch{
	[id(1)] HRESULT QueryProcessHandleInfo([in] ULONG ProcessId, [in, out] ULONG* ProcessHandleInfo);
};
[
	uuid(B27EB4FF-EAF5-4337-8D9D-B0058DDD0ED4),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{7315FA32-1837-4FE1-917B-2A02F5DBD7FC}")
]
library ATLSysHandleReaderLib
{
	importlib("stdole2.tlb");
	[
		uuid(7315FA32-1837-4FE1-917B-2A02F5DBD7FC)		
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[		
		uuid(0FF5960D-ED89-4B06-A8AC-E6D4DC4531DD)		
	]
	coclass InfoReader
	{
		[default] interface IInfoReader;
	};
};

